import Head from "next/head"
import Image from "next/image"
// import Title from 'atoms/Typography'
// import Header  from "atoms/"
import Header from "organisms/Header"

export default function Home() {
    return (
        <div className={""}>
            <Head>
                <title>Facturacion CFDI</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={"main"}>
                <Header color="##efe9dd"></Header>

                <p className={"description"}>
                    Get started by editing{" "}
                    <code className={"code"}>pages/index.js</code>
                </p>
            </main>

            <footer className={"footer"}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={"logo"}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}
