name: build-prod
on:
    push:
        branches:
            - master

jobs:
    connect-vpn-build-prod:
        name: Build Production
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@master

            - name: Install Open VPN
              run: sudo apt-get update && sudo apt install openvpn -y && sudo apt install expect

            - name: Connect VPN
              uses: golfzaptw/action-connect-ovpn@master
              id: connect_vpn
              with:
                  PING_URL: "127.0.0.1"
                  FILE_OVPN: ".github/vpn/config.ovpn"
                  SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
              env:
                  CA_CRT: ${{ secrets.CA_CRT}}
                  USER_CRT: ${{ secrets.USER_CRT }}
                  USER_KEY: ${{ secrets.USER_KEY }}

            - name: Connect to SSH and build
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.PROD_ENDPOINT }}
                  username: ${{ secrets.PROD_USER }}
                  password: ${{ secrets.PROD_PASSWORD }}
                  script: |
                      cd ${{ secrets.PROD_FOLDER }} &&

                      if [ -d facturacion-build ];
                      then
                        rm -Rf facturacion-build;
                      fi &&

                      git clone -b ${{ secrets.PROD_BRANCH }} --single-branch ${{ secrets.URL_REPO }} 'facturacion-build' &&
                      cd ./facturacion-build &&
                      yarn install &&
                      yarn build &&
                      cd .. &&

                      if [ -d facturacion-old ];
                      then
                        rm -Rf facturacion-old;
                      fi &&
                      mv './facturacion' './facturacion-old' &&

                      if [ -d facturacion ];
                      then
                        rm -Rf facturacion;
                      fi &&
                      mv './facturacion-build' './facturacion' &&
                      echo "Build successfully on \"http://${{ secrets.PROD_ENDPOINT }}/\""
            - name: kill vpn
              if: always()
              run: sudo killall openvpn
